/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Core API
 * Stack application core REST API.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EchoHTTPError,
  ProjectCreateRequest,
  ProjectProjectDTO
} from '../generated.schemas';

import { coreFetcher } from '../../orval-fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listProjectsResponse200 = {
  data: ProjectProjectDTO[]
  status: 200
}

export type listProjectsResponse500 = {
  data: EchoHTTPError
  status: 500
}

export type listProjectsResponseSuccess = (listProjectsResponse200) & {
  headers: Headers;
};
export type listProjectsResponseError = (listProjectsResponse500) & {
  headers: Headers;
};

export type listProjectsResponse = (listProjectsResponseSuccess | listProjectsResponseError)

export const getListProjectsUrl = () => {




  return `/projects`
}

/**
 * @summary List projects owned by the caller
 */
export const listProjects = async ( options?: RequestInit): Promise<listProjectsResponse> => {

  return coreFetcher<listProjectsResponse>(getListProjectsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListProjectsQueryKey = () => {
    return [
    `/projects`
    ] as const;
    }


export const getListProjectsQueryOptions = <TData = Awaited<ReturnType<typeof listProjects>>, TError = EchoHTTPError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>>, request?: SecondParameter<typeof coreFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListProjectsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProjects>>> = ({ signal }) => listProjects({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof listProjects>>>
export type ListProjectsQueryError = EchoHTTPError


export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = EchoHTTPError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProjects>>,
          TError,
          Awaited<ReturnType<typeof listProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof coreFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = EchoHTTPError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProjects>>,
          TError,
          Awaited<ReturnType<typeof listProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof coreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = EchoHTTPError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>>, request?: SecondParameter<typeof coreFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List projects owned by the caller
 */

export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = EchoHTTPError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>>, request?: SecondParameter<typeof coreFetcher>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListProjectsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createProjectResponse201 = {
  data: ProjectProjectDTO
  status: 201
}

export type createProjectResponse400 = {
  data: EchoHTTPError
  status: 400
}

export type createProjectResponseSuccess = (createProjectResponse201) & {
  headers: Headers;
};
export type createProjectResponseError = (createProjectResponse400) & {
  headers: Headers;
};

export type createProjectResponse = (createProjectResponseSuccess | createProjectResponseError)

export const getCreateProjectUrl = () => {




  return `/projects`
}

/**
 * @summary Create a project
 */
export const createProject = async (projectCreateRequest: ProjectCreateRequest, options?: RequestInit): Promise<createProjectResponse> => {

  return coreFetcher<createProjectResponse>(getCreateProjectUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(projectCreateRequest)
  }
);}





export const getCreateProjectMutationOptions = <TError = EchoHTTPError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{data: ProjectCreateRequest}, TContext>, request?: SecondParameter<typeof coreFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{data: ProjectCreateRequest}, TContext> => {

const mutationKey = ['createProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProject>>, {data: ProjectCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createProject(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof createProject>>>
    export type CreateProjectMutationBody = ProjectCreateRequest
    export type CreateProjectMutationError = EchoHTTPError

    /**
 * @summary Create a project
 */
export const useCreateProject = <TError = EchoHTTPError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{data: ProjectCreateRequest}, TContext>, request?: SecondParameter<typeof coreFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProject>>,
        TError,
        {data: ProjectCreateRequest},
        TContext
      > => {
      return useMutation(getCreateProjectMutationOptions(options), queryClient);
    }
